version: '3.7'
services:
    ## DB
    postgresql-dev:
        image: postgres:12.3-alpine
        volumes:
         - postgresql-dev-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /var/lib/postgresql/data/pgdata/
        networks:
            - back-end


    nginx:
        image: nginx:1.19.0-alpine
        restart: on-failure
        volumes:
            - './public:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PORT}:80'
        depends_on:
            - php


    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - '.:/usr/src/app'
        restart: on-failure
        env_file:
            - .env
        user: ${LOCAL_USER}
        networks:
            - back-end
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}


volumes:
    postgresql-dev-data:
        driver: local

networks:
    back-end:
